- include: ubuntu.yml

- include: nginx_ssl.yml
  when: deploy_ssl

- include: nginx_no_ssl.yml
  when: not deploy_ssl

- include: git.yml

- include: postgresql.yml

- include: dependencies.yml

- include: wsgi.yml
